# Generated by Django 4.1.2 on 2022-10-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
