# Generated by Django 4.1.2 on 2022-10-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_approval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
