# Generated by Django 4.1.2 on 2022-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_stu_height_field_stu_width_field_alter_stu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
