# Generated by Django 4.1.2 on 2022-10-21 07:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0004_stu_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelManagers(
            name='stu',
            managers=[
                ('hey', django.db.models.manager.Manager()),
            ],
        ),
    ]
