# Generated by Django 4.1.2 on 2022-10-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0005_stupost_alter_stu_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StuPost',
            new_name='Post',
        ),
    ]
