# Generated by Django 4.1.2 on 2022-10-22 15:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0006_rename_stupost_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stu',
            managers=[
                ('stusobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
